name: Build & Test & SonarCloud

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test & Coverage & Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean test jacocoTestReport sonar \
            -Dsonar.token=$SONAR_TOKEN